### ISSUE TITLE
你好 , 移动端上面对于NiceScroll插件适配有点问题 , 滑动屏幕的时候抖动的厉害

### ISSUE THREAD

**Issue by canye666** [xLong1029/xlong-resume#2]
特别是页面中下部分比较明显 , 点按屏幕滑动会造成 这一现象 , 如果划一下那种滑动是没问题的。

**Comment by xLong1029** [comment]
> 特别是页面中下部分比较明显 , 点按屏幕滑动会造成 这一现象 , 如果划一下那种滑动是没问题的。

问题已修复，已停用NiceScroll插件，改用css修改滚动条样式，能达到目的就行，不一定非要用插件，只是个美化效果
